# Generated by Django 2.2.3 on 2019-07-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_decode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Encode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_encode', models.CharField(max_length=100)),
            ],
        ),
    ]
