# Generated by Django 2.2.3 on 2019-07-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caesar_cipher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chipher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_encode', models.CharField(max_length=100)),
                ('content_decode', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Decode',
        ),
        migrations.DeleteModel(
            name='Encode',
        ),
    ]
