# Generated by Django 2.2.3 on 2019-07-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caesar_cipher', '0002_auto_20190729_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='chipher',
            name='shift',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
