# Generated by Django 2.2.3 on 2019-07-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caesar_cipher', '0003_chipher_shift'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chipher',
            new_name='Cipher',
        ),
    ]
